# 开发环境配置
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coder_dev
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:WTT713}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coder.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.coder: debug
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 开发环境特定配置
app:
  debug: true
  mock-enabled: true