# 生产环境配置
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://prod-db-cluster:3306/coder_prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coder.entity
  configuration:
    map-underscore-to-camel-case: true

# 生产环境特定配置
app:
  debug: false
  mock-enabled: false