# 测试环境配置
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://test-db:3306/coder_test
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:WTT713}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coder.entity
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.coder: info
    org.springframework: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 测试环境特定配置
app:
  debug: false
  mock-enabled: false