# 主配置文件
server:
  port: 8082

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: coder-auth
  config:
    import:
      - optional:nacos:application-${spring.profiles.active:dev}.yml
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: localhost:8848
        file-extension: yml
        group: DEFAULT_GROUP
        namespace: 5be21940-5a70-465d-8c2c-906b7baf4e10
        refresh-enabled: true
        import-check:
          enabled: false
      discovery:
        enabled: true
        server-addr: localhost:8848
        namespace: 5be21940-5a70-465d-8c2c-906b7baf4e10
        group: DEFAULT_GROUP

# OpenFeign配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        # 生产环境设为 NONE
        loggerLevel: ${FEIGN_LOG_LEVEL:BASIC}
      # 针对用户服务的特殊配置
      coder-user:
        connectTimeout: 3000
        readTimeout: 8000
        loggerLevel: ${FEIGN_LOG_LEVEL:BASIC}

# 日志配置
logging:
  level:
    root: info
    com.coder: debug
    org.apache.shiro: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}:%line] - %msg%n"
  file:
    name: ./logs/coder-auth.log