# 开发环境配置
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coder?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:WTT713}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: CoderAuthHikariCP
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 30000

  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:Sunset}
    database: ${REDIS_DATABASE:1}  # 使用不同的数据库
    timeout: 5000ms
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000ms


  # 邮件配置
  mail:
    host: smtp.163.com
    port: 587
    username: ${MAIL_USERNAME:your-email@qq.com} # 发送邮箱
    password: ${MAIL_PASSWORD:your-mail-password} # 邮箱授权码
    default-encoding: UTF-8
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          # 启用SMTP认证
          auth: true
          starttls:
            # 启用STARTTLS加密
            enable: true
            # 强制要求STARTTLS
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          # 163邮箱特殊配置
          ssl:
            enable: false

# 自定义邮件配置
mail:
  # 发送方信息
  from:
    # 发送方邮箱
    address: ${MAIL_FROM_ADDRESS:life@coder.com}
    # 发送方名称
    name: ${MAIL_FROM_NAME:Coder}

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coder.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Shiro配置
shiro:
  # 登录地址
  loginUrl: /auth/login
  # 成功地址
  successUrl: /auth/success
  # 未授权地址
  unauthorizedUrl: /auth/unauthorized
  # 启用会话
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: false
  # Web配置
  web:
    enabled: true

# JWT配置
jwt:
  # 密钥（建议生产环境使用更复杂的密钥）
  secret: coderServerSecretKeyForJWT2025
  # 过期时间（秒）7天
  expiration: 604800
  # Token前缀
  tokenPrefix: Bearer
  # Header名称
  headerName: Authorization