server:
  # 统一入口地址
  port: 8080

spring:
  application:
    # 网关服务名
    name: coder-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 5be21940-5a70-465d-8c2c-906b7baf4e10
        group: DEFAULT_GROUP

    gateway:
      # 路由配置
      routes:
        # 用户服务路由
          # 路由ID
        - id: user-service
          # lb表示负载均衡
          uri: lb://coder-user
          predicates:
            # 路径匹配规则
            - Path=/user/**
          filters:
            # 去掉路径前缀
            - StripPrefix=1

      # 跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: ["*"]
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600

# 日志配置
logging:
  level:
    root: info
    com.coder: debug
    org.springframework.cloud.gateway: debug
    reactor.netty: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{36}:%line] - %msg%n"
  file:
    name: ./logs/coder-gateway.log

# 网关监控
management:
  endpoints:
    web:
      exposure:
        include:
          - gateway      # 网关端点
          - health       # 健康检查
          - info         # 应用信息
          - metrics      # 性能指标
  endpoint:
    health:
      show-details: always
